// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLAoRGPP-zeePDBb5T0ZJayuc90xxMca8',
    appId: '1:957610956187:web:bb324fcab1cca75e943d3e',
    messagingSenderId: '957610956187',
    projectId: 'track-reads',
    authDomain: 'track-reads.firebaseapp.com',
    storageBucket: 'track-reads.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFxojyE-m7XEUgXakS5y5KiCQ2RdamhRA',
    appId: '1:957610956187:android:e0736f6300f9cf5d943d3e',
    messagingSenderId: '957610956187',
    projectId: 'track-reads',
    storageBucket: 'track-reads.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBorgUFps7W4VMV7-spjVifuJvr3PeYJoo',
    appId: '1:957610956187:ios:1cca1888bd220089943d3e',
    messagingSenderId: '957610956187',
    projectId: 'track-reads',
    storageBucket: 'track-reads.firebasestorage.app',
    iosBundleId: 'com.example.trackReads',
  );
}
